### ISSUE TITLE
Cannot login to schema.landrs.org via GitHub

### ISSUE THREAD

**Issue by chrissweet** [landrs-toolkit/schema.landrs.org#3]
If I go to schema.landrs.org and try and login it asked me to agree I have a Github account but then does not log me in. See screenshot using Firfox for login which shows login to James-landrs.
<img width="1313" alt="Screen Shot 2020-03-11 at 11 32 00 AM" src="https://user-images.githubusercontent.com/1945867/76434776-8370cb00-638c-11ea-813b-e6618eb11769.png">

**Comment by Omegaice** [comment]
This was caused by the application in github trying to use http://schema.landrs.org/ as the redirect URL when we now only allow https. Changed and should now be fixed.
